site_name: Project Yggdrasil
theme:
  name: material    
  favicon: images/favicon.ico
  logo: images/favicon.ico
  palette:
    scheme: slate
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview: 'Home.md'
  - 'Medicine':
    - 'Mod A': Mod_A.md
    - 'Mod B': Mod_B.md
    - 'Mod C': Mod_C.md

